# Generated by Django 5.1 on 2024-08-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
